version: "3.8"

services:

  aria2:
    image: aria2
    build: .
    env_file: .env
    container_name: "aria2_rpc"
    restart: always
    ports:
      - "6880:6800"
      - "6881-6999:6881-6999/udp"
    volumes:
      - ${DOWNLOAD_LOCATION}:/finished